### ISSUE TITLE
Is't working anymore since updating iTunes to 12.7

### ISSUE THREAD

**Issue by valeriyvan** [attheodo/cherrypick#6]

**Comment by cgarst** [comment]
You'll need to stay with iTunes 12.6 since 12.7 dropped support for apps. Apple now [maintains 12.6 separately](https://support.apple.com/en-us/HT208079). Cherrypick was recently fixed for 12.6.5.3 in a10be50b42e55275a30c2405d41cb6e98dbcb54a.
